runtime: nodejs10

instance_class: F1

handlers:
- url: /(.*\.(json|ico|png|js))$
  static_files: public/\1
  upload: public/.*\.(json|ico|png|js)$
  secure: always
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
